name: Emit "Nightly Published" Event on Release

on:
  release:
    types: [published]

jobs:
  trigger-check:
    strategy:
      matrix:
        repository: [
          software-mansion/cairo-lint,
          software-mansion/cairols,
          software-mansion/vscode-cairo
        ]
    runs-on: ubuntu-latest
    steps:
      - name: ${{ matrix.repository }} Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CAIRO_LANGUAGE_SERVICES_REPOS_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: new-scarb-nightly-published
          client-payload: '{"tag_name": "${{ github.event.release.tag_name }}" }'
