name: Emit "Nightly Published" Event on Release

on:
  release:
    types: [published]

# Extend with a matrix of repos if needed
jobs:
  trigger-check:
    runs-on: ubuntu-latest
    steps:
      - name: VSCode-Cairo Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.VSCODE_CAIRO_REPO_TOKEN }}
          repository: software-mansion/vscode-cairo
          event-type: new-scarb-nightly-published
          client-payload: '{"tag_name": ${{ github.event.release.tag_name }} }'
